"""
Expected column names for each timeframe, derived from the Environment Canada
bulk data API (observed using station 889, Vancouver Int'l A).

These are the columns after passing through ``_clean_column_names()``
(lowercased, spaces/hyphens → underscores, non-alphanumeric chars removed).
They are used to validate downloaded DataFrames.
"""

EXPECTED_COLUMNS: dict[str, list[str]] = {
    "daily": [
        "longitude_x",
        "latitude_y",
        "station_name",
        "climate_id",
        "datetime",
        "year",
        "month",
        "day",
        "data_quality",
        "max_temp_c",
        "max_temp_flag",
        "min_temp_c",
        "min_temp_flag",
        "mean_temp_c",
        "mean_temp_flag",
        "heat_deg_days_c",
        "heat_deg_days_flag",
        "cool_deg_days_c",
        "cool_deg_days_flag",
        "total_rain_mm",
        "total_rain_flag",
        "total_snow_cm",
        "total_snow_flag",
        "total_precip_mm",
        "total_precip_flag",
        "snow_on_grnd_cm",
        "snow_on_grnd_flag",
        "dir_of_max_gust_10s_deg",
        "dir_of_max_gust_flag",
        "spd_of_max_gust_kmh",
        "spd_of_max_gust_flag",
    ],
    "hourly": [
        "longitude_x",
        "latitude_y",
        "station_name",
        "climate_id",
        "datetime_lst",
        "year",
        "month",
        "day",
        "time_lst",
        "flag",
        "temp_c",
        "temp_flag",
        "dew_point_temp_c",
        "dew_point_temp_flag",
        "rel_hum_",
        "rel_hum_flag",
        "precip_amount_mm",
        "precip_amount_flag",
        "wind_dir_10s_deg",
        "wind_dir_flag",
        "wind_spd_kmh",
        "wind_spd_flag",
        "visibility_km",
        "visibility_flag",
        "stn_press_kpa",
        "stn_press_flag",
        "hmdx",
        "hmdx_flag",
        "wind_chill",
        "wind_chill_flag",
        "weather",
    ],
    "monthly": [
        "longitude_x",
        "latitude_y",
        "station_name",
        "climate_id",
        "datetime",
        "year",
        "month",
        "mean_max_temp_c",
        "mean_max_temp_flag",
        "mean_min_temp_c",
        "mean_min_temp_flag",
        "mean_temp_c",
        "mean_temp_flag",
        "extr_max_temp_c",
        "extr_max_temp_flag",
        "extr_min_temp_c",
        "extr_min_temp_flag",
        "total_rain_mm",
        "total_rain_flag",
        "total_snow_cm",
        "total_snow_flag",
        "total_precip_mm",
        "total_precip_flag",
        "snow_grnd_last_day_cm",
        "snow_grnd_last_day_flag",
        "dir_of_max_gust_10s_deg",
        "dir_of_max_gust_flag",
        "spd_of_max_gust_kmh",
        "spd_of_max_gust_flag",
    ],
}
